### ISSUE TITLE
Make course page responsive

### ISSUE THREAD

**Issue by vibrantachintya** [twowaits/tathastu-web#1]
course_page.html is not mobile responsive, make it mobile friendly.

**Comment by amohapatra123** [comment]
i want to work on this issue, please assign this to me.

**Comment by Amulya-coder** [comment]
@vibrantachintya I also want to contribute. Kindly Assign it to me.

**Comment by vibrantachintya** [comment]
I will assign you. But we have very strict guidelines to accept PR, so please keep that in mind.

**Comment by amohapatra123** [comment]
@vibrantachintya  i have already made the changes to make the page responsive and raised the PR you can check it #2  and merge it.
